
export interface ChatMessage {
  sender: 'user' | 'ai';
  content: string;
}

export enum Phase {
  WELCOME = "WELCOME",
  IDENTITY_PURPOSE = "IDENTITY_PURPOSE",
  SCOPE_RESPONSIBILITIES = "SCOPE_RESPONSIBILITIES",
  ORGANIZATIONAL_PROCESSES = "ORGANIZATIONAL_PROCESSES",
  CORE_TASKS = "CORE_TASKS",
  TEAM_STRUCTURE = "TEAM_STRUCTURE",
  INDICATORS_RESULTS = "INDICATORS_RESULTS",
  STAKEHOLDERS = "STAKEHOLDERS",
  TRANSFORMATION = "TRANSFORMATION",
  SUMMARY = "SUMMARY",
}
